version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URI: "postgresql://postgres:qwerty@db/test_project"
  db:
    image: postgres
    environment:
      POSTGRES_DB: test_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
